# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: rehf27
google_analytics: "UA-46755040-2"
title: End of the Line

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: End of the Line

description: Blog and website of rehf27, blogging mainly for tech and gaming. Opinions expressed are mine.
author:
  name: rehf27
  email: james@rehf27.com
  github: rehf27
  twitter: rehf27
  #pinterest: asd123
  #linkedin: asd123
  bio: Sitting in a chair; typing on a keyboard. #LTD
  email_md5: 04b940e1261d72125e53ace2dc26c16f

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: /assets/media/TW-Background.jpg

BASE_PATH:

gems:
  - jekyll-paginate
